### ISSUE TITLE
Make table borders visible in light mode

### ISSUE THREAD

**Issue by skoszuta** [FluffyLabs/graypaper-reader#32]
Currently switching to light mode makes table borders inside the document invisible because they remain white on a white background.

**Comment by tomusdrw** [comment]
I've took a look and it's going to be more difficult than just injecting styles. The tables are actually part of the background (assuming we still use pdf2htmlex). We can try to render the image on canvas and invert the colors to get the effect we need, currently the background images are just being hidden.
